from tools import get_tables, get_tables_tool, get_table_schemas_and_samples, get_table_schemas_tool, get_tables_semantic_search

from langchain_community.utilities import SQLDatabase
from langgraph.graph import StateGraph,  MessagesState, START, END
from langgraph.graph.state import CompiledStateGraph
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_openai import ChatOpenAI
from langchain_core.callbacks import get_usage_metadata_callback

from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer

from concurrent.futures import ThreadPoolExecutor, as_completed
from IPython.display import Image, display
from typing_extensions import Literal
from pydantic import BaseModel, Field
from datetime import datetime
from textwrap import dedent
from statistics import mean
from tqdm import tqdm
import numpy as np
import faiss
import json
import time

class State(MessagesState):
    llm: ChatOpenAI = Field(description="The LLM instance")
    llm_path: str = Field(description="Path to model on GPU node")
    secondary_llm: ChatOpenAI = Field(default=None, description="The LLM instance")
    secondary_llm_path: str = Field(default=None, description="Path to model on GPU node")
    tools: list = Field(default=[], description="List of tools")

    sql: str = Field(default=None, description="The final SQL generated by the sql_gen_llm.")
    tables: list[str] = Field(default=[], description="List of tables requested by get_table_schema_llm.")
    input_tokens: list[int] = Field(default=[], description="Number of input tokens to Generater LLM")
    output_tokens: list[int] = Field(default=[], description="Number of output tokens from Generater LLM")
    secondary_input_tokens: list[int] = Field(default=[], description="Number of tokens to tool LLM")
    secondary_output_tokens: list[int] = Field(default=[], description="Number of tokens tool LLM")

    

def user_node(state: State):
    """Represents the user"""

    return {"messages":state["messages"]}

def tool_node(state: State):
    """Performs the SQL statement execution tool call"""
    
    tools = state['tools']
    tools_by_name = {tool.name: tool for tool in tools}

    result = []
    table_list = state['tables']
    for tool_call in state["messages"][-1].tool_calls:
        tool = tools_by_name[tool_call["name"]]
        args = tool_call["args"].copy()
        if "table_list" in args:
            table_list.append(args["table_list"])
        observation = tool.invoke(tool_call["args"])
        result.append(ToolMessage(content=observation, tool_call_id=tool_call["id"]))
    return {"messages":result, "tables":table_list}


class Generated_SQL(BaseModel):
    '''Generate a SQL statement for the user.'''
    sql: str = Field(description="The SQL Statement")

# LLM Calls
dialect = 'MySQL'
def gen_llm_call(state: State):
    """LLM decides whether to call a tool or not"""
    llm = state['llm']
    structured_sql_gen_llm = llm.with_structured_output(Generated_SQL,
                    strict=True,
                    include_raw=True
                )
    
    system_message_content = dedent(
        """**Task Description:** 
        You are an SQL database expert tasked with writing a SQL query. A previous method has analyzed the original question and evidence, and retrieved the most relevant tables from the database. Your role is to analyze the original question based on the provided evidence and database schema, and then provide a SQL query. 

        **Procedure:** 
        1. Review Database Schema: 
        - Examine the table creation statements to understand the database structure. 
        2. Analyze Query Requirements: 
        - Original Question: Consider what information the query is supposed to retrieve. 
        - Hint: Use the provided evidence to understand the relationships and conditions relevant to the query. 
        3. Correct the Query: 
        - Generate the SQL query to address the original question, ensuring it correctly fetches the requested data according to the database schema and query requirements.  

        **Output Format:**  
        Present your query as a single line of SQL code. Ensure there are no line breaks within the query.""")   
    with get_usage_metadata_callback() as cb:
        response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + state["messages"])
        metadata = cb.usage_metadata[state['llm_path']]
        state["input_tokens"].append(metadata["input_tokens"])
        state["output_tokens"].append(metadata["output_tokens"])
    
    # Returns parsed as None when tool is called
    if response['parsed']:
        return {"messages": response['raw'], "sql": response['parsed'].sql, "input_tokens":state["input_tokens"], "output_tokens":state["output_tokens"]}
    # Tool call is in raw
    else:
        return {"messages": response['raw']}
    

    # LLM Calls
dialect = 'MySQL'
def search_llm_call(state: State):
    """LLM decides whether to call a tool or not"""
    structured_sql_gen_llm = state['llm'].with_structured_output(Generated_SQL,
                strict=True,
                tools=state['tools'],
                include_raw=True
                )
    
    system_message_content = dedent("""You are a helpful {dialect} generation agent. Your task is to generate a {dialect} query for the user request.
                                Provided to you are:
                                1. The tables in the data you will be generating your query for.
                                2. A tool that will retrieve schema information and data value examples of given tables.
                                3. The user's request.
                                    
                                Use the tool to retrieve information to inform your query generation.

                                Your final response is the SQL statement. Follow the Output Format Instruction 
                                ### Table Selection: ###
                                - You can retrieve multiple tables at one time.
                                - You can use the tool more than once.
                                - Only query for tables in the provided list.
                                - DO NOT request tables that are not already listed in by a tool
                                - When in doubt between similar tables, retrieve both - it's better to have extra context than miss critical information
                                - Consider foreign key relationships - if you need data from table A that references table B, retrieve both

                                ### Output Format Instruction ###
                                - Return ONLY the raw SQL query.
                                - DO NOT include any explanations, introductory text, or natural language commentary before or after the query.
                                - DO NOT put the SQL inside a markdown code block (e.g., do not use ```sql ... ```).
                                - DO NOT include new lines "\\n /no_think"
                                """.format(dialect="MySQL"))   
    

    with get_usage_metadata_callback() as cb:
        response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + state["messages"])
        metadata = cb.usage_metadata[state['llm_path']]
        state["input_tokens"].append(metadata["input_tokens"])
        state["output_tokens"].append(metadata["output_tokens"])
    
    # Returns parsed as None when tool is called
    if response['parsed']:
        return {"messages": response['raw'], "sql": response['parsed'].sql, "input_tokens":state["input_tokens"], "output_tokens":state["output_tokens"]}
    # Tool call is in raw
    else:
        return {"messages": response['raw']}

    

def should_continue(state: State) -> Literal["environment", END]:
    """Decide if we should continue the loop or stop based upon whether the LLM made a tool call"""

    messages = state["messages"]
    last_message = messages[-1]
    # If the LLM makes a tool call, then perform an action
    if last_message.tool_calls:
        return "Action"
    # Otherwise, we stop (reply to the user)
    return END