from tools import get_tables, get_tables_tool, get_table_schemas_and_samples, get_table_schemas_tool, get_tables_semantic_search, get_distinct_values_tool

from langchain_community.utilities import SQLDatabase
from langgraph.graph import StateGraph,  MessagesState, START, END
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_openai import ChatOpenAI
from langchain_core.callbacks import get_usage_metadata_callback

from typing_extensions import Literal
from pydantic import BaseModel, Field
from textwrap import dedent



class State(MessagesState):
    llm: ChatOpenAI = Field(description="The LLM instance")
    llm_path: str = Field(description="Path to model on GPU node")
    secondary_llm: ChatOpenAI = Field(default=None, description="The LLM instance")
    secondary_llm_path: str = Field(default=None, description="Path to model on GPU node")
    tools: list = Field(default=[], description="List of tools")
    retries: int = Field(default=0, description="List of tools")
    max_retries:int = Field(default=0, description="List of tools")

    sql: str = Field(default=None, description="The final SQL generated by the sql_gen_llm.")
    tables: list[str] = Field(default=[], description="List of tables requested by get_table_schema_llm.")
    input_tokens: list[int] = Field(default=[], description="Number of input tokens to Generater LLM")
    output_tokens: list[int] = Field(default=[], description="Number of output tokens from Generater LLM")
    secondary_input_tokens: list[int] = Field(default=[], description="Number of tokens to tool LLM")
    secondary_output_tokens: list[int] = Field(default=[], description="Number of tokens tool LLM")

with open(r'src\V4\prompts\fix_llm_prompt.txt', 'r') as f:
    tables_by_domain = f.read()    

def get_tables_by_domain():
    return tables_by_domain

def user_node(state: State):
    """Represents the user"""

    return {"messages":state["messages"]}

def tool_node(state: State):
    """Performs the SQL statement execution tool call"""
    
    tools = state['tools']
    tools_by_name = {tool.name: tool for tool in tools}

    result = []
    table_list = state['tables']
    for tool_call in state["messages"][-1].tool_calls:
        try:
            tool = tools_by_name[tool_call["name"]]
            args = tool_call["args"].copy()
            # if "table_list" in args:
            #     table_list.append(args["table_list"])
            observation = tool.invoke(tool_call["args"])
            result.append(ToolMessage(content=observation, tool_call_id=tool_call["id"]))
        except Exception as e:
            result.append(ToolMessage(content=str(e), tool_call_id=tool_call["id"]))
    return {"messages":result, "tables":table_list}


class Generated_SQL(BaseModel):
    '''Generate a SQL statement for the user.'''
    sql: str = Field(description="The SQL Statement")

# LLM Calls
dialect = 'MySQL'
def gen_llm_call(state: State):
    """LLM decides whether to call a tool or not"""
    llm = state['llm']
    structured_sql_gen_llm = llm.with_structured_output(Generated_SQL,
                    strict=True,
                    include_raw=True
                )
    table_schemas = get_table_schemas_and_samples(state['tables'])
    system_message_content = dedent(
        """
        **Task Description:** 
        You are an SQL database expert tasked with writing a SQL query. A previous method has analyzed the original question and evidence, and retrieved the most relevant tables from the database. Your role is to analyze the original question based on the provided evidence and database schema, and then provide a SQL query. 

        **Procedure:** 
        1. Review Database Schema: 
        - Examine the table creation statements to understand the database structure. 
        2. Analyze Query Requirements: 
        - Original Question: Consider what information the query is supposed to retrieve. 
        - Hint: Use the provided evidence to understand the relationships and conditions relevant to the query. 
        3. Generate the Query: 
        - Generate the SQL query to address the original question, ensuring it correctly fetches the requested data according to the database schema and query requirements.  

        **Output Format:**  
        Present your query as a single line of SQL code. Ensure there are no line breaks within the query.
        
        **TABLE SCHEMAS**
        {table_schemas}
        """).format(table_schemas=table_schemas)   
    with get_usage_metadata_callback() as cb:
        response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + [state["messages"][0]])
        metadata = cb.usage_metadata[state['llm_path']]
        state["input_tokens"].append(metadata["input_tokens"])
        state["output_tokens"].append(metadata["output_tokens"])
    
    # Returns parsed as None when tool is called
    if response['parsed']:
        return {"messages": response['raw'], "sql": response['parsed'].sql, "input_tokens":state["input_tokens"], "output_tokens":state["output_tokens"],"retries": state["retries"]}
    # Tool call is in raw
    else:
        return {"messages": response['raw']}
    
class LLMSearchOutput(BaseModel):

    '''Explore database and return findings for SQL Generator'''
    tables: list[str] = Field(description="a list of tables crucial for generating sql query for the user.")
    # LLM Calls
dialect = 'MySQL'

def search_llm_call(state: State):
    """LLM decides whether to call a tool or not"""
    structured_sql_gen_llm = state['llm'].with_structured_output(LLMSearchOutput,
                    strict=True,
                    tools=state['tools'],
                    include_raw=True
                )

    ## CRITICAL: You can retrieve a MAXIMUM of {MAX_TABLES} tables. Be selective and choose only the most relevant tables.
    system_message_content = dedent(        
        """You are part of a SQL query generation pipeline. Your role is to identify which database tables from the list are needed to answer the user's question.

        ## Your Task
        Analyze the user's question and select relevant tables from the provided list to pass to the `get_table_schemas` tool.

        ** Task Description **
        **Table Selection:**
        - Only select from the tables provided by previous tool calls.
        - DO NOT request tables that are not already listed in by a tool
        - When in doubt between similar tables, retrieve both - it's better to have extra context than miss critical information
        - Consider foreign key relationships - if you need data from table A that references table B, retrieve both

        **TABLES**
        All tables are in the same database accessible through the provided tools. The following tables are organized by domain.

        **Tools:**
        Use the tools available to search the database and retrieve schema metadata and values.
        1. get_table_schemas_tool 
        - Description: Query the database for up to 5 create table statements
        - Args: table_names: List[str] of table names
        - Returns: Formatted string containing schema and sample data for each table

        **TABLES**
        The following tables are in the same database, accessible through get_table_schemas_tool. The following tables are organized by domain.
        Example:
        Domain 1:
        * Table 1
        * Table 2
        * Table 3

        Tables:
        {table_list}

        SELECT the tables most likely to be relavent to the user query.
        """.format(table_list=tables_by_domain))   
    

    with get_usage_metadata_callback() as cb:
        response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + state["messages"])
        metadata = cb.usage_metadata[state['llm_path']]
        state["input_tokens"].append(metadata["input_tokens"])
        state["output_tokens"].append(metadata["output_tokens"])
    
    # Returns parsed as None when tool is called
    if response['parsed']:
        return {"messages": response['raw'], "tables": response['parsed'].tables, "input_tokens":state["input_tokens"], "output_tokens":state["output_tokens"],"retries": state["retries"]}
    # Tool call is in raw
    else:
        return {"messages": response['raw'],"retries": state["retries"]+1}
    

def search_gen_llm_call(state: State):
    """LLM decides whether to call a tool or not"""
    structured_sql_gen_llm = state['llm'].with_structured_output(Generated_SQL,
                strict=True,
                tools=state['tools'],
                include_raw=True
                )
    

    
    system_message_content = dedent(
        """
        **Task Description:** 
        You are an SQL database expert tasked writing a SQL query. Your role is to analyze the original question based on the provided evidence, and use available tools to gather information on the database schema, then generate an SQL Query . 

        **Procedure:** 
        1. Analyze Query Requirements: 
        - Original Question: Consider what information the query is supposed to retrieve. 
        - Hint: Use the provided evidence to understand the relationships and conditions relevant to the query. 
        2. Review Database Schema: 
        - Examine the provided tables of tables
        - Examine the results of previous tool calls to understand the database structure.
        - Make additional tool calls to retreive crucial database information.                     
        3. Generate the Query: 
        - Generate the SQL query to address the original question, ensuring it correctly fetches the requested data according to the database schema and query requirements.

        **Tools:**
        Use the tools available to search the database and retrieve schema metadata and values.
        1. get_table_schemas_tool 
        - Description: Query the database for up to 5 create table statements
        - Args: table_names: List[str] of table names
        - Returns: Formatted string containing schema and sample data for each table

        **TABLES**
        All tables are in the same database accessible through the provided tools. The following tables are organized by domain.
        Example:
        Domain 1:
        * Table 1
        * Table 2
        * Table 3

        Tables:
        {table_list}

        """.format(table_list=tables_by_domain))   
    

    with get_usage_metadata_callback() as cb:
        response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + state["messages"])
        metadata = cb.usage_metadata[state['llm_path']]
        state["input_tokens"].append(metadata["input_tokens"])
        state["output_tokens"].append(metadata["output_tokens"])
    
    # Returns parsed as None when tool is called
    if response['parsed']:
        return {"messages": response['raw'], "sql": response['parsed'].sql, "input_tokens":state["input_tokens"], "output_tokens":state["output_tokens"],"retries": state["retries"]}
    # Tool call is in raw
    else:
        return {"messages": response['raw'],"retries": state["retries"]+1}

    

def should_continue(state: State) -> Literal["environment", END]:
    """Decide if we should continue the loop or stop based upon whether the LLM made a tool call"""
    messages = state["messages"]
    last_message = messages[-1]
    # If the LLM makes a tool call, then perform an action
    if last_message.tool_calls and state['retries'] <= state['max_retries']:
        return "Action"
    # Otherwise, we stop (reply to the user)
    return END

def should_continue_llm_search(state: State) -> Literal["environment", END]:
    """Decide if we should continue the loop or stop based upon whether the LLM made a tool call"""
    messages = state["messages"]
    last_message = messages[-1]
    # If the LLM makes a tool call, then perform an action
    if last_message.tool_calls and state['retries'] <= state['max_retries']:
        return "Action"
    # Otherwise, we stop (reply to the user)
    return "Generate"










# Nodes
def get_table_schema_llm_calls(state: State):
    """LLM decides whether to call a tool or not"""

    system_message_content = dedent(
        """You are part of a SQL query generation pipeline. Your role is to identify which database tables from the list are needed to answer the user's question.

        ## Your Task
        Analyze the user's question and select relevant tables from the provided list to pass to the `get_table_schemas` tool.

        ## Guidelines
        ## CRITICAL: You can retrieve a MAXIMUM of {MAX_TABLES} tables. Be selective and choose only the most relevant tables.
        **Table Selection:**
        - Only select from the tables provided by previous tool calls.
        - DO NOT request tables that are not already listed in by a tool
        - When in doubt between similar tables, retrieve both - it's better to have extra context than miss critical information
        - Consider foreign key relationships - if you need data from table A that references table B, retrieve both
        """)
    
    with get_usage_metadata_callback() as cb:
        response = llm_with_get_table_schemas_tool.invoke(state["messages"] + [SystemMessage(content=system_message_content)] )        
        metadata = cb.usage_metadata[tool_model_path]
        search_input_tokens  = metadata["input_tokens"]
        search_output_tokens = metadata["output_tokens"]
    
    return {"messages":[response], 'search_input_tokens': search_input_tokens, 'search_output_tokens':search_output_tokens}


# Nodes
def SQLGenerator_llm_call(state: State):
    """LLM decides whether to call a tool or not"""

    system_message_content = dedent("""You are a helpful SQL generation agent designed to generate {dialect} statements.
                                Given a user input provided, use the retrieved database schema and values gernate an SQL statement that answers the user's question.

                                Your final response is the SQL statement. Follow the Output Format Instruction 
                                ### Output Format Instruction ###
                                - Return ONLY the raw SQL query.
                                - DO NOT include any explanations, introductory text, or natural language commentary before or after the query.
                                - DO NOT put the SQL inside a markdown code block (e.g., do not use ```sql ... ```).
                                - DO NOT include new lines "\\n /no_think"
                                """.format(dialect="MySQL"))   
    response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + state["messages"])
    with get_usage_metadata_callback() as cb:
        response = llm_with_get_table_schemas_tool.invoke([SystemMessage(content=system_message_content)] + state["messages"])        
        metadata = cb.usage_metadata[tool_model_path]
        gen_input_tokens  = metadata["input_tokens"]
        gen_output_tokens = metadata["output_tokens"]
    return {"sql": response.sql, 'search_input_tokens': gen_input_tokens, 'search_output_tokens':gen_output_tokens}




