from langchain.tools import tool
from langchain_community.utilities import SQLDatabase
from langgraph.graph import StateGraph, MessagesState, START, END
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_openai import ChatOpenAI
from langchain_core.callbacks import get_usage_metadata_callback

from transformers import AutoTokenizer

from concurrent.futures import ThreadPoolExecutor, as_completed
from IPython.display import Image, display
from typing_extensions import Literal
from pydantic import BaseModel, Field
from datetime import datetime
from textwrap import dedent
from statistics import mean
from tqdm import tqdm
import json
import time


with open(r'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev-main\mysql\mini_dev_mysql.json') as f:
    mini_dev_sql = json.load(f)

database = SQLDatabase.from_uri("mysql+pymysql://readonly-agent:bird@localhost:3306/bird_mini_dev")
version = 'Agentic'
model_name = 'pto-oss-20b'
file_name= f'{model_name}'
model_path = "/home/012155624/.cache/huggingface/hub/models--openai--gpt-oss-20b/snapshots/6cee5e81ee83917806bbde320786a8fb61efebee"
max_completion_tokens = 2048
vLLM_max_model_len = '8k'

error_catching = True

mini_dev_sql = mini_dev_sql

llm = ChatOpenAI(
    base_url="http://localhost:8000/v1",
    api_key="EMPTY",
    model=model_path,
    temperature=0,
    max_completion_tokens=max_completion_tokens
)

class State(MessagesState):
    tables: list[str] = Field(default=[], description="List of tables requested by get_table_schema_llm.")
    input_tokens: list[int] = Field(default=[], description="Number of tokens")
    output_tokens: list[int] = Field(default=[], description="Number of tokens")  
    justification: str = Field(default=None, description="Justification for the final SQL.")
    sql: str = Field(default=None, description="The final SQL generated by the sql_gen_llm.")
    




def user_node(state: State):
    """Represents the user"""

    return {"messages":state["messages"]}

def get_tables_node():
    """Performs the tool call"""

    query = f"SHOW TABLES;"

    tables = database.run(query)
    response = "Result of SHOW TABLES query: \n" + tables
    result = ToolMessage(content=response, tool_call_id="get_tables_node")
    return {"messages":result}
    



# Tools
@tool
def get_table_schemas(table_list: list[str]) -> str:
    """Get detailed information about a list of tables including columns, types, constraints, and the top 3 rows.
    
    Args:
        table_names: List of table name strings

    Returns:
        Formatted string containing schema and sample data for each table
    """

    database_info = []
    for table_name in table_list:
        try:
            # Get schema
            schema_query = f"SHOW CREATE TABLE `{table_name}`;"
            schema = database.run(schema_query)
            
            # Get first 3 rows
            sample_query = f"SELECT * FROM `{table_name}` LIMIT 3;"
            sample_data = database.run(sample_query)
            
            # Format for LLM
            table_info = dedent(f"""
                Table: {table_name}
                Schema: {schema}
                Sample Data (first 3 rows): {sample_data}
                ---
                """) 
            database_info.append(table_info)
        except:
            database_info.append(f"Table '{table_name}' does not exist or is not accessible.")


    # Combine all table information
    formatted_output = "\n".join(database_info)

    return formatted_output

    
def tool_node(state: State):
    """Performs the SQL statement execution tool call"""

    result = []
    table_list = state['tables']
    for tool_call in state["messages"][-1].tool_calls:
        tool = tools_by_name[tool_call["name"]]
        args = tool_call["args"].copy()
        if "table_list" in args:
            table_list.append(args["table_list"])
        observation = tool.invoke(tool_call["args"])
        result.append(ToolMessage(content=observation, tool_call_id=tool_call["id"]))
    return {"messages":result, "tables":table_list}





# LLM with Structured output and Tools
class Generated_SQL(BaseModel):
    '''Generate a SQL statement for the user.'''
    justification: str = Field(description="A short explanation for the reasoning of the generated SQL.")
    sql: str = Field(description="The SQL Statement")


tools = [get_table_schemas]
tools_by_name = {tool.name: tool for tool in tools}

structured_sql_gen_llm = llm.with_structured_output(Generated_SQL,
                    strict=True,
                    tools=tools,
                    include_raw=True
                )


# LLM Calls
dialect = 'MySQL'
def agent_llm_call(state: State):
    """LLM decides whether to call a tool or not"""
    
    system_message_content = dedent("""You are a helpful {dialect} generation agent. Your task is to generate a {dialect} query for the user request.
                                Provided to you are:
                                1. The tables in the data you will be generating your query for.
                                2. A tool that will retrieve schema information and data value examples of given tables.
                                3. The user's request.
                                    
                                Use the tool to retrieve information to inform your query generation.

                                Your final response is the SQL statement. Follow the Output Format Instruction 
                                ### Table Selection: ###
                                - You can retrieve multiple tables at one time.
                                - You can use the tool more than once.
                                - Only query for tables in the provided list.
                                - DO NOT request tables that are not already listed in by a tool
                                - When in doubt between similar tables, retrieve both - it's better to have extra context than miss critical information
                                - Consider foreign key relationships - if you need data from table A that references table B, retrieve both

                                ### Output Format Instruction ###
                                - Return ONLY the raw SQL query.
                                - DO NOT include any explanations, introductory text, or natural language commentary before or after the query.
                                - DO NOT put the SQL inside a markdown code block (e.g., do not use ```sql ... ```).
                                - DO NOT include new lines "\\n /no_think"
                                """.format(dialect="MySQL"))   
    with get_usage_metadata_callback() as cb:
        response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + state["messages"])
        metadata = cb.usage_metadata[model_path]
        state["input_tokens"].append(metadata["input_tokens"])
        state["output_tokens"].append(metadata["output_tokens"])
    
    # Returns parsed as None when tool is called
    if response['parsed']:
        return {"messages": response['raw'], "sql": response['parsed'].sql, "justification": response['parsed'].justification, "input_tokens":state["input_tokens"], "output_tokens":state["output_tokens"]}
    # Tool call is in raw
    else:
        return {"messages": response['raw']}

    

def should_continue(state: State) -> Literal["environment", END]:
    """Decide if we should continue the loop or stop based upon whether the LLM made a tool call"""

    messages = state["messages"]
    last_message = messages[-1]
    # If the LLM makes a tool call, then perform an action
    if last_message.tool_calls:
        return "Action"
    # Otherwise, we stop (reply to the user)
    return END





# Build workflow
agent_builder = StateGraph(State)

# Add nodes
agent_builder.add_node("user", user_node)
agent_builder.add_node("agent_llm_call", agent_llm_call)
agent_builder.add_node("environment", tool_node)

# Add edges to connect nodes

agent_builder.add_edge(START, "user")
agent_builder.add_edge("user", "agent_llm_call")
agent_builder.add_conditional_edges(
    "agent_llm_call",
    should_continue,
    {
        # Name returned by should_continue : Name of next node to visit
        "Action": "environment",
        END: END,
    },
)
agent_builder.add_edge("environment", "agent_llm_call")

agent = agent_builder.compile() 

def call_agent(i, entry):
    call_start_time = time.time()

    table_list = get_tables_node()

    messages = [HumanMessage(content=dedent("""{question} You may find this informaiton helpful: {evidence}
                                            Here are the all tables available in the database:
                                            {table_list}""".format(
                    question=entry['question'],
                    evidence=entry['evidence'],
                    table_list=table_list)))]
    
    if(error_catching):
        try:
            response = agent.invoke({"messages": messages, "tables": [], "input_tokens": [], "output_tokens": []})
            result= f'{response['sql']}\t----- bird -----\t{entry["db_id"]}'

            call_elapsed = time.time() - call_start_time
            call_elapsed_min = call_elapsed/60

            meta_data = {'tables': response['tables'], 
                        'tokens': {'input_tokens': response['input_tokens'], 'output_tokens': response['output_tokens']},
                        'latency_s': call_elapsed,
                        'latency_m': call_elapsed_min,
                        'db_id': entry["db_id"]}
        except Exception as e:
            result = f"ERROR: {str(e)}"
            call_elapsed = time.time() - call_start_time
            call_elapsed_min = call_elapsed/60
            meta_data = {'tables': ['ERROR'], 
                'tokens': {'tool_input_tokens': -1, 'tool_output_tokens':-1,
                    'gen_input_tokens': -1, 'gen_output_tokens': -1},
                'latency_s': -1,
                'latency_m': -1,
                'db_id': entry["db_id"]}


    else: 
        response = agent.invoke({"messages": messages, "tables": [], "input_tokens": [], "output_tokens": []})
        result = f'{response['sql']}\t----- bird -----\t{entry["db_id"]}'

        call_elapsed = time.time() - call_start_time
        call_elapsed_min = call_elapsed/60

        meta_data = {'tables': response['tables'], 
                    'tokens': {'input_tokens': response['input_tokens'], 'output_tokens': response['output_tokens']},
                    'latency_s': call_elapsed,
                    'latency_m': call_elapsed_min,
                    'db_id': entry["db_id"]}
    
    return i, result, meta_data

results = {}
metadatadict = {}
start_time = time.time()

max_workers = 10  # Adjust based on kv_cache
with ThreadPoolExecutor(max_workers=max_workers) as executor:
    # Submit all tasks
    futures = {
        executor.submit(call_agent, i, entry): i 
        for i, entry in enumerate(mini_dev_sql)
    }
    
    # Process completed tasks with progress bar
    for future in tqdm(as_completed(futures), total=len(futures)):
        i, result, metadata = future.result()
        results[str(i)] = result
        metadatadict[str(i)] = metadata

results = dict(sorted(results.items(), key=lambda x: int(x[0])))
metadata = dict(sorted(metadatadict.items(), key=lambda x: int(x[0])))

elapsed = time.time() - start_time
elapsed_min = elapsed/60

dt_now = datetime.now().strftime("%Y%m%d_%H%M%S")

#metadatadict

#metadatadict = 'average': averages , 'individual': metadata

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev-main\sql_result\{version}\results_{file_name}_{dt_now}.json', 'w') as f:
    json.dump(results, f, indent=4)

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev-main\sql_result\{version}\metadata\metadata_{file_name}_{dt_now}.json', 'w') as f:
    json.dump(metadatadict, f, indent=4)

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev-main\sql_result\{version}\metadata\results_{file_name}_{dt_now}.log', 'w') as f:
    averages ={}
    # token_keys = ['tool_input_tokens', 'tool_output_tokens','gen_input_tokens', 'gen_output_tokens']
    # averages = {
    #     key: mean(entry['tokens'][key] for entry in metadatadict.values() if entry['tokens'][key] != -1) 
    #     for key in token_keys
    # }
    
    #maximum = {key: max(entry['tokens'][key] for entry in metadatadict.values()) for key in token_keys}
    averages['latency_s'] = mean(entry['latency_s'] for entry in metadatadict.values()if entry['latency_s']!= -1)
    averages['latency_m'] = mean(entry['latency_m'] for entry in metadatadict.values()if entry['latency_m']!= -1)
    
    # f.write(f"{len(metadatadict)} entries):\n")
    # f.write(f"Tool Input Tokens:  {averages['tool_input_tokens']:.2f}\n")
    # f.write(f"Tool Output Tokens: {averages['tool_output_tokens']:.2f}]\n")
    # f.write(f"Avg Tool Input Tokens:   {maximum['tool_input_tokens']:.2f}\n")
    # f.write(f"Avg Tool Output Tokens:  {maximum['tool_output_tokens']:.2f}\n")

    # f.write(f"Avg Gen Input Tokens:   {averages['gen_input_tokens']:.2f}\n")
    # f.write(f"Avg Gen Output Tokens:  {averages['gen_output_tokens']:.2f}\n")
    # f.write(f"Max Gen Input Tokens:   {maximum['gen_input_tokens']:.2f}\n")
    # f.write(f"Max Gen Output Tokens:  {maximum['gen_output_tokens']:.2f}\n")   

    f.write(f'Total Latency (seconds):  {round(elapsed,2)}s / Latency (minutes):  {round(elapsed_min,2)}min\n')
    f.write(f"Avg  Latency (seconds):  {averages['latency_s']:.2f}/ Avg  Latency (minutes):  {averages['latency_m']:.4f}\n")

    # f.write(f'Langgraph gen_llm max_tokens: {max_completion_tokens}\n')
    # f.write(f'vLLM model max-model-len: {vLLM_max_model_len}\n')