from langchain.tools import tool
from langchain_community.utilities import SQLDatabase
from langgraph.graph import StateGraph, MessagesState, START, END
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_openai import ChatOpenAI
from langchain_core.callbacks import get_usage_metadata_callback

from transformers import AutoTokenizer

from concurrent.futures import ThreadPoolExecutor, as_completed
from IPython.display import Image, display
from pydantic import BaseModel, Field
from datetime import datetime
from textwrap import dedent
from statistics import mean
from tqdm import tqdm
import json
import time


with open(r'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev-main\mysql\mini_dev_mysql.json') as f:
    mini_dev_sql = json.load(f)

database = SQLDatabase.from_uri("mysql+pymysql://readonly-agent:bird@localhost:3306/bird_mini_dev")
version = 'Sequential'
model_name = 'Qwen3-8B_Qwen3-14B'
file_name= f'{model_name}_one-gpu'
model_path = "/home/012155624/.cache/huggingface/hub/models--Qwen--Qwen3-8B/snapshots/b968826d9c46dd6066d109eabc6255188de91218"
max_completion_tokens = 2048
vLLM_max_model_len = '8k'

error_catching = False

mini_dev_sql = mini_dev_sql


llm = ChatOpenAI(
    base_url="http://localhost:8000/v1",
    api_key="EMPTY",
    model=model_path,
    temperature=0,
    max_completion_tokens=max_completion_tokens
)


class State(MessagesState):
    tables: list[str] = Field(default=None, description="List of tables requested by get_table_schema_llm.")
    tool_input_tokens: int = Field(default=None, description="Number of tokens")
    tool_output_tokens: int = Field(default=None, description="Number of tokens")
    gen_input_tokens: int = Field(default=None, description="Number of tokens")
    gen_output_tokens: int = Field(default=None, description="Number of tokens")  
    justification: str = Field(default=None, description="Justification for the final SQL.")
    sql: str = Field(default=None, description="The final SQL generated by the sql_gen_llm.")
    

def user_node(state: State):
    """Represents the user"""

    return {"messages":state["messages"]}

def get_tables_node(state: State):
    """Performs the tool call"""

    query = f"SHOW TABLES;"

    tables = database.run(query)
    response = "Result of SHOW TABLES query: \n" + tables
    result = ToolMessage(content=response, tool_call_id="get_tables_node")
    return {"messages":result}
    



# Tools
@tool
def get_table_schemas(table_list: list[str]) -> str:
    """Get detailed information about a list of tables including columns, types, constraints, and the top 3 rows.
    
    Args:
        table_names: List of table name strings

    Returns:
        Formatted string containing schema and sample data for each table
    """

    database_info = []
    for table_name in table_list:
        try:
            # Get schema
            schema_query = f"SHOW CREATE TABLE `{table_name}`;"
            schema = database.run(schema_query)
            
            # Get first 3 rows
            sample_query = f"SELECT * FROM `{table_name}` LIMIT 3;"
            sample_data = database.run(sample_query)
            
            # Format for LLM
            table_info = dedent(f"""
                Table: {table_name}
                Schema: {schema}
                Sample Data (first 3 rows): {sample_data}
                ---
                """) 
            database_info.append(table_info)
        except:
            database_info.append(f"Table '{table_name}' does not exist or is not accessible.")


    # Combine all table information
    formatted_output = "\n".join(database_info)

    return formatted_output

#Change out LLM

# LLM with Tools
tools = [get_table_schemas]
tools_by_name = {tool.name: tool for tool in tools}
llm_with_get_table_schemas_tool = llm.bind_tools(tools)
MAX_TABLES = 6

# Nodes
def get_table_schema_llm_calls(state: State):
    """LLM decides whether to call a tool or not"""

    system_message_content = dedent(
        """You are part of a SQL query generation pipeline. Your role is to identify which database tables from the list are needed to answer the user's question.

        ## Your Task
        Analyze the user's question and select relevant tables from the provided list to pass to the `get_table_schemas` tool.

        ## Guidelines
        ## CRITICAL: You can retrieve a MAXIMUM of {MAX_TABLES} tables. Be selective and choose only the most relevant tables.
        **Table Selection:**
        - Only select from the tables provided by previous tool calls.
        - DO NOT request tables that are not already listed in by a tool
        - When in doubt between similar tables, retrieve both - it's better to have extra context than miss critical information
        - Consider foreign key relationships - if you need data from table A that references table B, retrieve both
        /no_think
        """)
    
    with get_usage_metadata_callback() as cb:
        response = llm_with_get_table_schemas_tool.invoke(state["messages"] + [SystemMessage(content=system_message_content)] )
        metadata = cb.usage_metadata[model_path]
        input_tokens = metadata["input_tokens"]
        output_tokens = metadata["output_tokens"]

    
    return {"messages":[response], "tool_input_tokens":input_tokens, "tool_output_tokens":output_tokens}

def get_table_schema_tool_node(state: State):
    """Performs the SQL statement execution tool call"""

    result = []
    table_list = []
    for tool_call in state["messages"][-1].tool_calls:
        tool = tools_by_name[tool_call["name"]]
        args = tool_call["args"].copy()
        
        # Enforce limit
        if "table_list" in args:
            table_list = args["table_list"]
            if len(args["table_list"]) > MAX_TABLES:
                args["table_list"] = args["table_list"][:MAX_TABLES]
        
        observation = tool.invoke(tool_call["args"])
        result.append(ToolMessage(content=observation, tool_call_id=tool_call["id"]))
    return {"messages":result, "tables":table_list}



dialect = 'MySQL'

class Generated_SQL(BaseModel):
    '''Generate a SQL statement for the user.'''
    justification: str = Field(description="A short explanation for the reasoning of the generated SQL.")
    sql: str = Field(description="The SQL Statement")
    

structured_sql_gen_llm = llm.with_structured_output(Generated_SQL,
                    strict=True
                )

# Nodes
def SQLGenerator_llm_call(state: State):
    """LLM decides whether to call a tool or not"""

    system_message_content = dedent("""You are a helpful SQL generation agent designed to generate {dialect} statements.
                                Given a user input provided, use the retrieved database schema and values gernate an SQL statement that answers the user's question.

                                Your final response is the SQL statement. Follow the Output Format Instruction 
                                ### Output Format Instruction ###
                                - Return ONLY the raw SQL query.
                                - DO NOT include any explanations, introductory text, or natural language commentary before or after the query.
                                - DO NOT put the SQL inside a markdown code block (e.g., do not use ```sql ... ```).
                                - DO NOT include new lines "\\n /no_think"
                                """.format(dialect="MySQL"))   
    
    with get_usage_metadata_callback() as cb:
        response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + state["messages"][0:1] + state["messages"][2:])
        metadata = cb.usage_metadata[model_path]
        input_tokens = metadata["input_tokens"]
        output_tokens = metadata["output_tokens"]

    return {"sql": response.sql, "justification": response.justification, "gen_input_tokens":input_tokens, "gen_output_tokens":output_tokens}

# Build workflow
agent_builder = StateGraph(State)

# Add nodes
agent_builder.add_node("user", user_node)
agent_builder.add_node("get_tables", get_tables_node)
agent_builder.add_node("get_table_schemas_llm", get_table_schema_llm_calls)
agent_builder.add_node("get_table_schemas_tool", get_table_schema_tool_node)
agent_builder.add_node("sqlgen_llm_call", SQLGenerator_llm_call)

# Add edges to connect nodes
agent_builder.add_edge(START, "user")
agent_builder.add_edge("user", "get_tables")
agent_builder.add_edge("get_tables", "get_table_schemas_llm")
agent_builder.add_edge("get_table_schemas_llm", "get_table_schemas_tool")
agent_builder.add_edge("get_table_schemas_tool", "sqlgen_llm_call")
agent_builder.add_edge("sqlgen_llm_call", END)

agent = agent_builder.compile() 

def call_agent(i, entry):
    call_start_time = time.time()


    messages = [HumanMessage(content=dedent("""{question} You may find this informaiton helpful: {evidence}""".format(
                    question=entry['question'],
                    evidence=entry['evidence'],)))]
    
    if(error_catching):
        try:
            response = agent.invoke({"messages": messages})
            result= f'{response['sql']}\t----- bird -----\t{entry["db_id"]}'

            call_elapsed = time.time() - call_start_time
            call_elapsed_min = call_elapsed/60

            meta_data = {'tables': response['tables'], 
                        'tokens': {'tool_input_tokens': response['tool_input_tokens'], 'tool_output_tokens': response['tool_output_tokens'],
                            'gen_input_tokens': response['gen_input_tokens'], 'gen_output_tokens': response['gen_output_tokens']},
                        'latency_s': call_elapsed,
                        'latency_m': call_elapsed_min,
                        'db_id': entry["db_id"]}
        except Exception as e:
            result = f"ERROR: {str(e)}"
            call_elapsed = time.time() - call_start_time
            call_elapsed_min = call_elapsed/60
            meta_data = {'tables': ['ERROR'], 
                'tokens': {'tool_input_tokens': -1, 'tool_output_tokens':-1,
                    'gen_input_tokens': -1, 'gen_output_tokens': -1},
                'latency_s': -1,
                'latency_m': -1,
                'db_id': entry["db_id"]}


    else: 
        response = agent.invoke({"messages": messages})
        result = f'{response['sql']}\t----- bird -----\t{entry["db_id"]}'

        call_elapsed = time.time() - call_start_time
        call_elapsed_min = call_elapsed/60

        meta_data = {'tables': response['tables'], 
                    'tokens': {'tool_input_tokens': response['tool_input_tokens'], 'tool_output_tokens': response['tool_output_tokens'],
                    'gen_input_tokens': response['gen_input_tokens'], 'gen_output_tokens': response['gen_output_tokens']},
                    'latency_s': call_elapsed,
                    'latency_m': call_elapsed_min,
                    'db_id': entry["db_id"]}
    
    return i, result, meta_data

results = {}
metadatadict = {}
start_time = time.time()

max_workers = 10  # Adjust based on kv_cache
with ThreadPoolExecutor(max_workers=max_workers) as executor:
    # Submit all tasks
    futures = {
        executor.submit(call_agent, i, entry): i 
        for i, entry in enumerate(mini_dev_sql)
    }
    
    # Process completed tasks with progress bar
    for future in tqdm(as_completed(futures), total=len(futures)):
        i, result, metadata = future.result()
        results[str(i)] = result
        metadatadict[str(i)] = metadata

results = dict(sorted(results.items(), key=lambda x: int(x[0])))
metadata = dict(sorted(metadatadict.items(), key=lambda x: int(x[0])))

elapsed = time.time() - start_time
elapsed_min = elapsed/60

dt_now = datetime.now().strftime("%Y%m%d_%H%M%S")

#metadatadict

#metadatadict = 'average': averages , 'individual': metadata

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev-main\sql_result\{version}\results_{file_name}_{dt_now}.json', 'w') as f:
    json.dump(results, f, indent=4)

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev-main\sql_result\{version}\metadata\metadata_{file_name}_{dt_now}.json', 'w') as f:
    json.dump(metadatadict, f, indent=4)

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev-main\sql_result\{version}\metadata\results_{file_name}_{dt_now}.log', 'w') as f:
    token_keys = ['tool_input_tokens', 'tool_output_tokens','gen_input_tokens', 'gen_output_tokens']
    averages = {
        key: mean(entry['tokens'][key] for entry in metadatadict.values() if entry['tokens'][key] != -1) 
        for key in token_keys
    }

    maximum = {key: max(entry['tokens'][key] for entry in metadatadict.values()) for key in token_keys}
    averages['latency_s'] = mean(entry['latency_s'] for entry in metadatadict.values()if entry['latency_s']!= -1)
    averages['latency_m'] = mean(entry['latency_m'] for entry in metadatadict.values()if entry['latency_m']!= -1)
    
    f.write(f"{len(metadatadict)} entries):\n")
    f.write(f"Tool Input Tokens:  {averages['tool_input_tokens']:.2f}\n")
    f.write(f"Tool Output Tokens: {averages['tool_output_tokens']:.2f}]\n")
    f.write(f"Avg Tool Input Tokens:   {maximum['tool_input_tokens']:.2f}\n")
    f.write(f"Avg Tool Output Tokens:  {maximum['tool_output_tokens']:.2f}\n")

    f.write(f"Avg Gen Input Tokens:   {averages['gen_input_tokens']:.2f}\n")
    f.write(f"Avg Gen Output Tokens:  {averages['gen_output_tokens']:.2f}\n")
    f.write(f"Max Gen Input Tokens:   {maximum['gen_input_tokens']:.2f}\n")
    f.write(f"Max Gen Output Tokens:  {maximum['gen_output_tokens']:.2f}\n")   

    f.write(f'Total Latency (seconds):  {round(elapsed,2)}s / Latency (minutes):  {round(elapsed_min,2)}min\n')
    f.write(f"Avg  Latency (seconds):  {averages['latency_s']:.2f}/ Avg  Latency (minutes):  {averages['latency_m']:.4f}\n")

    f.write(f'Langgraph gen_llm max_tokens: {max_completion_tokens}\n')
    f.write(f'vLLM model max-model-len: {vLLM_max_model_len}\n')