from langchain.tools import tool, ToolRuntime
from langchain_community.utilities import SQLDatabase
from langgraph.graph import StateGraph, MessagesState, START, END
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_openai import ChatOpenAI

#from transformers import AutoTokenizer

from IPython.display import Image, display
from pymysql.err import ProgrammingError
from pydantic import BaseModel, Field
from typing_extensions import Literal
from datetime import datetime
from textwrap import dedent
from pprint import pprint
from pathlib import Path
from tqdm import tqdm
import subprocess
import json
import time
import requests
import argparse
import ast

import os
from dotenv import load_dotenv

with open(r'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev_main\mysql\mini_dev_mysql.json') as f:
    mini_dev_sql = json.load(f)

database = SQLDatabase.from_uri("mysql+pymysql://readonly-agent:bird@localhost:3306/bird_mini_dev")

model_name = 'Qwen3-4B'
model_path = "/home/012155624/.cache/huggingface/hub/models--Qwen--Qwen3-4B/snapshots/1cfa9a7208912126459214e8b04321603b3df60c/"
max_completion_tokens = 1024

@tool
def execute_query(query: str) -> str:
    """Execute a SQL SELECT query and return the results.
    
    Only SELECT statements are permitted for data safety.
    Returns formatted results or error messages.
    
    Args:
        query: The SQL SELECT query to execute
    """
    # Strip whitespace and check query type
    query_stripped = query.strip()
    query_upper = query_stripped.upper()
    
    # Block non-SELECT queries
    dangerous_keywords = ['INSERT', 'UPDATE', 'DELETE', 'DROP', 'CREATE', 'ALTER', 'TRUNCATE']
    if any(query_upper.startswith(keyword) for keyword in dangerous_keywords):
        return f"Error: Only SELECT queries are allowed. Detected forbidden operation."
    
    if not query_upper.startswith('SELECT'):
        return "Error: Query must start with SELECT."
    
    try:
        result = db.run(query_stripped)
        if not result or result.strip() == '':
            return "Query executed successfully but returned no results."
        return result
    except Exception as e:
        return f"Error executing query: {str(e)}\nQuery was: {query_stripped}"
    

class State(MessagesState):
    tables: list[str] = Field(default=None, description="List of tables requested by get_table_schema_llm.")
    table_schemas: str = Field(default=None, description="List of table schemas retrieved by get_table_schema_tool.")
    justification: str = Field(default=None, description="Justification for the final SQL.")
    sql: str = Field(default=None, description="The final SQL generated by the sql_gen_llm.")
    

def user_node(state: State):
    """Represents the user"""

    return {"messages":state["messages"]}

def get_tables_node(state: State):
    """Performs the tool call"""

    query = f"SHOW TABLES;"

    tables = database.run(query)
    response = "Result of SHOW TABLES query: \n" + tables
    result = ToolMessage(content=response, tool_call_id="get_tables_node")
    return {"messages":result}
    
llm = ChatOpenAI(
    base_url="http://localhost:8000/v1",
    api_key="EMPTY",
    model=model_path,
    temperature=0,
    max_completion_tokens=max_completion_tokens
)


# Tools
@tool
def get_table_schemas(table_list: list[str]) -> str:
    """Get detailed information about a list of tables including columns, types, constraints, and the top 3 rows.
    
    Args:
        table_names: List of table name strings

    Returns:
        Formatted string containing schema and sample data for each table
    """

    database_info = []
    for table_name in table_list:
        try:
            # Get schema
            schema_query = f"SHOW CREATE TABLE `{table_name}`;"
            schema = database.run(schema_query)
            
            # Get first 3 rows
            sample_query = f"SELECT * FROM `{table_name}` LIMIT 3;"
            sample_data = database.run(sample_query)
            
            # Format for LLM
            table_info = dedent(f"""
                Table: {table_name}
                Schema: {schema}
                Sample Data (first 3 rows): {sample_data}
                ---
                """) 
            database_info.append(table_info)
        except:
            database_info.append(f"Table '{table_name}' does not exist or is not accessible.")


    # Combine all table information
    formatted_output = "\n".join(database_info)

    return formatted_output

#Change out LLM

# LLM with Tools
tools = [get_table_schemas]
tools_by_name = {tool.name: tool for tool in tools}
llm_with_get_table_schemas_tool = llm.bind_tools(tools)
MAX_TABLES = 6

# Nodes
def get_table_schema_llm_calls(state: State):
    """LLM decides whether to call a tool or not"""

    system_message_content = dedent(
        """You are part of a SQL query generation pipeline. Your role is to identify which database tables from the list are needed to answer the user's question.

        ## Your Task
        Analyze the user's question and select relevant tables from the provided list to pass to the `get_table_schemas` tool.

        ## Guidelines
        ## CRITICAL: You can retrieve a MAXIMUM of {MAX_TABLES} tables. Be selective and choose only the most relevant tables.
        **Table Selection:**
        - Only select from the tables provided by previous tool calls.
        - DO NOT request tables that are not already listed in by a tool
        - When in doubt between similar tables, retrieve both - it's better to have extra context than miss critical information
        - Consider foreign key relationships - if you need data from table A that references table B, retrieve both
        /no_think
        """)
    response = llm_with_get_table_schemas_tool.invoke(state["messages"] + [SystemMessage(content=system_message_content)] )
    
    return {"messages":[response]}

def get_table_schema_tool_node(state: State):
    """Performs the SQL statement execution tool call"""

    result = []
    table_list = []
    for tool_call in state["messages"][-1].tool_calls:
        tool = tools_by_name[tool_call["name"]]
        args = tool_call["args"].copy()
        
        # Enforce limit
        if "table_list" in args:
            table_list = args["table_list"]
            if len(args["table_list"]) > MAX_TABLES:
                args["table_list"] = args["table_list"][:MAX_TABLES]
        
        observation = tool.invoke(tool_call["args"])
        result.append(ToolMessage(content=observation, tool_call_id=tool_call["id"]))
    return {"messages":result, "tables":table_list}



dialect = 'MySQL'

class Generated_SQL(BaseModel):
    '''Generate a SQL statement for the user.'''
    justification: str = Field(description="A short explanation for the reasoning of the generated SQL.")
    sql: str = Field(description="The SQL Statement")
    

structured_sql_gen_llm = llm.with_structured_output(Generated_SQL,
                    strict=True
                )

# Nodes
def SQLGenerator_llm_call(state: State):
    """LLM decides whether to call a tool or not"""

    system_message_content = dedent("""You are a helpful SQL generation agent designed to generate {dialect} statements.
                                Given a user input provided, use the retrieved database schema and values gernate an SQL statement that answers the user's question.

                                Your final response is the SQL statement. Follow the Output Format Instruction 
                                ### Output Format Instruction ###
                                - Return ONLY the raw SQL query.
                                - DO NOT include any explanations, introductory text, or natural language commentary before or after the query.
                                - DO NOT put the SQL inside a markdown code block (e.g., do not use ```sql ... ```).
                                - DO NOT include new lines "\\n"
                                """.format(dialect="MySQL"))   
    response = structured_sql_gen_llm.invoke([SystemMessage(content=system_message_content)] + state["messages"][0:1] + state["messages"][2:])
    return { "sql": response.sql, 
            "justification": response.justification}
    

# Build workflow
agent_builder = StateGraph(State)

# Add nodes
agent_builder.add_node("user", user_node)
agent_builder.add_node("get_tables", get_tables_node)
agent_builder.add_node("get_table_schemas_llm", get_table_schema_llm_calls)
agent_builder.add_node("get_table_schemas_tool", get_table_schema_tool_node)
agent_builder.add_node("sqlgen_llm_call", SQLGenerator_llm_call)


# Add edges to connect nodes
agent_builder.add_edge(START, "user")
agent_builder.add_edge("user", "get_tables")
agent_builder.add_edge("get_tables", "get_table_schemas_llm")
agent_builder.add_edge("get_table_schemas_llm", "get_table_schemas_tool")
agent_builder.add_edge("get_table_schemas_tool", "sqlgen_llm_call")
agent_builder.add_edge("sqlgen_llm_call", END)

agent = agent_builder.compile()

# Show the agent
#display(Image(agent.get_graph(xray=True).draw_mermaid_png()))

results = {}
tables = {}
start_time = time.time()

for i, entry in tqdm(enumerate(mini_dev_sql), total=len(mini_dev_sql  )):

    messages = [HumanMessage(content=dedent("""{question} You may find this informaiton helpful: {evidence}""".format(
                        question=entry['question'],
                        evidence=entry['evidence'],)))]
    # response = agent.invoke({"messages": messages})
    # results[str(i)] = f'{response['sql']}\t----- bird -----\t{entry["db_id"]}'
    # tables[str(i)] = f'{response['tables']}\t----- bird -----\t{entry["db_id"]}'
    try:
        response = agent.invoke({"messages": messages})
        results[str(i)] = f'{response['sql']}\t----- bird -----\t{entry["db_id"]}'
        tables[str(i)] = f'{response['tables']}\t----- bird -----\t{entry["db_id"]}'
    except Exception as e:
        results[str(i)] = f"ERROR: {str(e)}"

elapsed = time.time() - start_time
elapsed_min = elapsed/60

dt_now = datetime.now().strftime("%Y%m%d_%H%M%S")

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev_main\sql_result\V2\results_v2_{model_name}_{dt_now}.json', 'w') as f:
    json.dump(results, f, indent=4)

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev_main\sql_result\V2\tables\tables_v2_{model_name}_{dt_now}.json', 'w') as f:
    json.dump(results, f, indent=4)

with open(rf'C:\Users\peter\Documents\SJSU\Thesis\code\mini_dev_main\sql_result\Baseline\results_baseline_{model_name}_{dt_now}.log', 'w') as f:
    f.write(f'Latency: {elapsed}s / {elapsed_min}m\n')
    f.write(f'Max_tokens: {max_completion_tokens}')